# Generated by Django 4.2.16 on 2024-12-09 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordatoriomantenimiento',
            name='mantenimiento',
        ),
        migrations.RemoveField(
            model_name='recordatoriomantenimiento',
            name='vehiculo',
        ),
        migrations.DeleteModel(
            name='Alerta',
        ),
        migrations.DeleteModel(
            name='RecordatorioMantenimiento',
        ),
    ]
